### ISSUE TITLE
css animation 动画

### ISSUE THREAD

**Issue by divcssjs** [divcssjs/blog#31]
```css
.box {
  animation: boxAnimation 50s linear infinite normal;
}

@keyframes boxAnimation {
  0% {
    transform: translateY(-1000px);
  }

  100% {
    transform: translateY(0);
  }
}
```
